# Confusion Matrix

In [19]:
from tensorflow import keras
import os
import numpy as np

In [18]:
model = keras.models.load_model('G:\\Model2')

In [20]:
base_dir = 'G:/dataset/FPC'
test_dir = os.path.join(base_dir, 'test')

In [21]:
test_ds = keras.utils.image_dataset_from_directory(test_dir,
                                                      label_mode='categorical',
                                                      batch_size=64,
                                                      image_size=(160,160))

Found 600 files belonging to 3 classes.


In [42]:
labels = np.array([])
images = np.array([]).reshape(-1, 160, 160 , 3)
for img_batch, lbls in test_ds:
    images = np.concatenate([images, img_batch], axis=0)
    labels = np.append(labels, np.argmax(lbls, axis=-1))

images = images / 255

In [43]:
Y_pred = np.argmax(model.predict(images), axis=-1)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix
print('Confusion Matrix')
print(confusion_matrix(labels, Y_pred))

Confusion Matrix
[[200   0   0]
 [  1 195   4]
 [  0   6 194]]
